### PR TITLE
spec: support exists() on directories pre-cache

### PR DESCRIPTION
**Pull request by isidentical**
```
import secrets
from adlfs import AzureBlobFileSystem

BUCKET = 'bucket/'
FOLDER = f'{BUCKET}{secrets.token_hex(12)}/'

fs = AzureBlobFileSystem(**opts)
fs.touch(FOLDER + 'foo')
fs.touch(FOLDER + 'bar')
fs.invalidate_cache()

print(fs.exists(FOLDER))
fs.ls(fs._parent(FOLDER))
print(fs.exists(FOLDER))
```

While the first one is returning False, after the cache the second one is returning true. The reason is that, the `exists()` implementation first tries to check whether a such a directory exists by traversing the cache and when it fails it tries to check if a blob named `path` exists though if the directory is not cached, it doesn't check for that. This patch makes it fallback to the default implementation which is basically checking the result of `info()`.

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]
Looks good. One small question.

**Comment by isidentical** [comment]
> One small question.

I can't see the question.

**Comment by TomAugspurger** [comment]
Strange, my review was lost. The gist was: should the `.rstrip` call be `.rstrip("/", 1)` to avoid cases where the path is `/path/to/file//` (if that's even allowed)?

**Review by TomAugspurger — APPROVED** [review]
CI is passing now. Planning to merge in a few hours.

**Comment by TomAugspurger** [comment]
Thanks @isidentical!

**Pull request merged**
