### PR TITLE
pin azure-storage-blob < 12.4.0

### PR DESCRIPTION
**Pull request by raybellwaves**
It seems the latest version of `azure-storage-blob` is causing an import error of `adlfs` (https://github.com/dask/adlfs/issues/83)

I've pinned the version of `azure-storage-blob` to azure-storage-blob>=12.0.0,<12.4.0.

Do we need to do anything else?

### CODE REVIEW

**Comment by martindurant** [comment]
Does not seem to solve:
```
E   ImportError: cannot import name 'BlobPrefix' from 'azure.storage.blob._models' (/usr/share/miniconda/lib/python3.8/site-packages/azure/storage/blob/_models.py)
```
line from install:

https://dev.azure.com/dask-dev/dask/_build/results?buildId=1516&view=logs&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=8ee03a6f-7be6-5ac9-b016-f8ce8dbc1d4b&l=139

still got 12.4.0

**Comment by raybellwaves** [comment]
CI failure is probably related to the error
```
ImportError while loading conftest '/home/vsts/work/1/s/adlfs/tests/conftest.py'.
adlfs/__init__.py:1: in <module>
    from .core import AzureDatalakeFileSystem
adlfs/core.py:14: in <module>
    from azure.storage.blob._models import BlobBlock, BlobPrefix
E   ImportError: cannot import name 'BlobPrefix' from 'azure.storage.blob._models' (/usr/share/miniconda/lib/python3.8/site-packages/azure/storage/blob/_models.py)

##[error]Bash exited with code '4'.
```
Would I have pin the version in the CI code as well?

**Comment by martindurant** [comment]
I think in dev-requirements.txt

**Comment by raybellwaves** [comment]
Not related to this PR but did some house keeping and removed `meta.yaml` as we now have the conda version file at https://github.com/conda-forge/adlfs-feedstock/blob/master/recipe/meta.yaml

**Comment by raybellwaves** [comment]
Curious does it need a new version 0.3.2 -> 0.3.3?

**Comment by martindurant** [comment]
Would be good to release, unless the necessary fix to make the pin unnecessary again is not too far in the future.

**Comment by raybellwaves** [comment]
How do I bump the version? Couldn't find 0.3.2 in the repo. Is it done via Releases?

**Comment by martindurant** [comment]
It is done by annotated tags (which is maybe what you said); but better to ask the maintainer, @hayesgb , to do this, and to venture an opinion on fixing the import in the first place.

**Pull request merged**
